### PR TITLE
Add Missing Type Annotations - Partial

### LINKED ISSUE #18: Missing Type Annotations
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_emc2101/\_\_init\_\_.py:71
- [ ] adafruit_emc2101/\_\_init\_\_.py:83
- [ ] adafruit_emc2101/\_\_init\_\_.py:219
- [ ] adafruit_emc2101/\_\_init\_\_.py:267
- [ ] adafruit_emc2101/\_\_init\_\_.py:300
- [ ] adafruit_emc2101/\_\_init\_\_.py:312
- [ ] adafruit_emc2101/\_\_init\_\_.py:323
- [ ] adafruit_emc2101/\_\_init\_\_.py:334
- [ ] adafruit_emc2101/emc2101_lut.py:57
- [ ] adafruit_emc2101/emc2101_lut.py:74
- [ ] adafruit_emc2101/emc2101_lut.py:79
- [ ] adafruit_emc2101/emc2101_lut.py:86
- [ ] adafruit_emc2101/emc2101_lut.py:142
- [ ] adafruit_emc2101/emc2101_lut.py:165
- [ ] adafruit_emc2101/emc2101_lut.py:177
- [ ] adafruit_emc2101/emc2101_lut.py:209
- [ ] adafruit_emc2101/emc2101_lut.py:220
- [ ] adafruit_emc2101/emc2101_lut.py:232

### PR DESCRIPTION
**Pull request by tcfranks**
resolves #18 

This is a PARTIALLY COMPLETE solution - still completing work on objects and methods in emc2101_fanspeed.py....Wanted to get the others (__init__.py, emc2101_lut.py, emc2101_ext.py, and emc2101_enums.py) up for feedback and review.

### CODE REVIEW

**Comment by tekktrik** [comment]
Do you intend to keep it all in this one review, or break it up across multiple PRs?  If it's the latter, I'll unlink the issue so it doesn't get lost or forgotten. :)

**Comment by tcfranks** [comment]
I guess I anticipated feedback on the others that would require correction, and that I’d gety the last file annotated and completed with the rest. 

There were pretty lot hanging fruit, so if that’s not the case, unlink the or and I’ll push the last when I get it done. I won’t get to it before this evening, at the earliest.

**Review by FoamyGuy — COMMENTED** [review]
The changes that are included here thus far look good to me. Nothing particular jumps out to me that would need to be changed from the portion that is here at the moment.

**Comment by tcfranks** [comment]
Thank you @FoamyGuy .  I've been dragging my feet, I know.  I'll be out of town for two weeks.  I'll try to wrap this up when I get back.

**Review by FoamyGuy — APPROVED** [review]
Going to merge this and we can work on the remaining in a new PR

**Pull request merged**
